### PR TITLE
Log admin user in history for related actions

### PR DESCRIPTION
**Pull request by Callek**
We should log who (admin) does what manual actions in slaveloan.

### CODE REVIEW

**Comment by Callek** [comment]
Now a PR, r? @djmitche

**Comment by djmitche** [comment]
Looks good.  Can you add a Python logger message, too?  That will eventually make it to MozDef, and this is the sort of info opsec would like to see.

**Comment by Callek** [comment]
updated.. r?  I'm not certain on the best logging message, but this should do for now.

**Comment by djmitche** [comment]
:+1:

**Pull request merged**
