### PR TITLE
Test Coverage for slaveloan should be greater than 60%

### PR DESCRIPTION
**Pull request by Callek**
Get test coverage for slaveloan to 60% or greater for v0.1

### CODE REVIEW

**Comment by Callek** [comment]
Not yet up to 60% coverage, but I am close. I'm interested in any feedback on the tests so far though.

**Comment by djmitche** [comment]
Looking good so far!

**Comment by Callek** [comment]
With this we're >60%, I suspect we'll dip a bit below with the new code I'll be adding (in untested areas) before v0.1, but I think we're good for this round.

@djmitche r?

**Comment by djmitche** [comment]
Looks good.  Please bump up the value in `validate.sh` too, before landing -- maybe to 55%?

**Pull request merged**
